### ISSUE TITLE
"property 'defineCommand' of undefined" error is appearing on calling apis provided by webdriver-js-extender

### ISSUE THREAD

**Issue by helloabhi** [angular/webdriver-js-extender#15]
In the before annotation, I have written below code

 var webdriver = require('selenium-webdriver');

        var extendedWebdriver = require('webdriver-js-extender').extend(webdriver);

        extendedWebdriver.setNetworkConnection(5);

Please see the error mentioned below

 Failed: Cannot read property 'defineCommand' of undefined
  Stack:
    TypeError: Cannot read property 'defineCommand' of undefined
        at Extender.defineCommand (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/extender.ts:33:19)
        at CommandDefinition.compile (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/command_definition.ts:13:16)
        at Object.extend (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/index.ts:65:50)
        at Object.<anonymous> (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:45:66)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:110:25
        at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    From: Task: Run beforeEach in control flow
        at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:35:5)
        at Object.<anonymous> (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:27:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

**Comment by NickTomlin** [comment]
Hi there, 

Can you provide the following:

- Operating System and version
- Node.js version
- Selenium version
- Protractor version (if applicable)

Thanks!

**Comment by Rochester87** [comment]
I have same issue.
Windows 10 - 1511
Node - v6.9.1
Selenium - 2.20.0
Selenium webdriver - 3.4.0
Protractor  - 5.1.2 (first tried with 4.10.0, and then updated to 5.1.2)
Appium - 1.6.1

**Comment by helloabhi** [comment]
Please look into the information provided

MacOS Sierra 10.12.4
Node - v7.9.0
Appium - 1.6.1
Protractor - 5.1.1

**Comment by NickTomlin** [comment]
What are you passing to `extend`? I believe this should be an instance of webdriver, not the module exported by `require('selenium-webdriver')`

**Comment by bvasilchik** [comment]
I have been trying to test this as well and I'm getting the same exact error. Haven't had much luck finding much information 

MacOS Sierra 10.12.4
Node - v6.9.5
Appium - 1.6.0
Protractor - 5.1.2

**Comment by Nahuel990** [comment]
Hi!

I am getting the same Issue 

MacOS Mojave10.14
Node v8.12.0
Appium 1.9.1
Protractor 5.4.1
